insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('<h1>CPU, CU and ALU</h1>\n    <p>CPU stands for Central Processing Unit. The CPU is the primary component of a computer that processes instructions. It runs the operating system and applications, \t\t\tconstantly receiving input from the user or active software programs.</p>\n    <p>CU stands for Control Unit and is an integrated circuit in a processor that controls the input and output. It receives instructions from a program, then passes them to\n    the arithmetic logic unit ALU.</p>\n    <p>ALU stands for Arithmetic Logic Unit and is a digital circuit that is used to perform arithmetic and logic operations. It represents the fundamental building block of \t\tthe central processing unit of a computer. Modern CPUs contain very powerful and complex ALUs.</p>', 1, 'Chapter 1 - Processor Components');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('<h1> Some content </h1>', 2, 'Chapter 2 - Processor Performance');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('<h1> Some Content </h1>', 3, 'Chapter 3 - Types of Processors');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 4, 'Chapter 4 - Input Devices');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 5, 'Chapter 5 - Output Devices');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 6, 'Chapter 6 - Storage Devices');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 7, 'Chapter 7 - Functions of an Operating System');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 8, 'Chapter 8 - Types of Operating Systems');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 9, 'Chapter 9 - The nature of applications');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 10, 'Chapter 10 - Programming Language Translators');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 11, 'Chapter 11 - Systems Analysis Methods');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 12, 'Chapter 12 - Writing and Following Methods');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 13, 'Chapter 13 - Programming Paradigms');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 14, 'Chapter 14 - Assembly Language');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 15, 'Chapter 15 - Compression, Encryption and Hashing');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 16, 'Chapter 16 - Database Concepts');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 17, 'Chapter 17 - Relational Databases and Normalisation');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 18, 'Chapter 18 - Introduction to SQL');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 19, 'Chapter 19 - Defining and Updating tables using SQL');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 20, 'Chapter 20 - Transaction Processing');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 21, 'Chapter 21 - Structure of the Internet');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 22, 'Chapter 22 - Internet Communication');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 23, 'Chapter 23 - Network Security and Threats');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 24, 'Chapter 24 - HTML and CSS');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 25, 'Chapter 25 - Web Forms and JavaScript');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 26, 'Chapter 26 - Search Engine Indexing');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 27, 'Chapter 27 - Client-Server and Peer-to-Peer');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 28, 'Chapter 28 - Primitive Data Types, Binary and Hexadecimal');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 29, 'Chapter 29 - ASCII and Unicode');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 30, 'Chapter 30 - Binary Arithmetic');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 31, 'Chapter 31 - Floating Point Arithmetic');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 32, 'Chapter 32 - Bitwise Manipulation and Masks');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 33, 'Chapter 33 - Arrays, Tuples and Records');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 34, 'Chapter 34 - Queues');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 35, 'Chapter 35 - Lists and Linked Lists');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 36, 'Chapter 36 - Stacks');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 37, 'Chapter 37 - Hash Tables');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 38, 'Chapter 38 - Graphs');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 39, 'Chapter 39 - Trees');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 40, 'Chapter 40 - Logic Gates and Truth Tables');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 41, 'Chapter 41 - Simplifying Boolean Expressions');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 42, 'Chapter 42 - Karnaugh Maps');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 43, 'Chapter 43 - Adders and D-type Flip-Flops');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 44, 'Chapter 44 - Computing Related Legislation');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 45, 'Chapter 45 - Ethical, Moral and Cultural Issues');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 46, 'Chapter 46 - Privacy and Censorship');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 47, 'Chapter 47 - Thinking Abstractly');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 48, 'Chapter 48 - Thinking Ahead');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 49, 'Chapter 49 - Thinking Procedurally');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 50, 'Chapter 50 - Thinking Logically, Thinking Concurrently');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 51, 'Chapter 51 - Problem Recognition');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 52, 'Chapter 52 - Problem Solving');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 53, 'Chapter 53 - Programming Basics');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 54, 'Chapter 54 - Selection');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 55, 'Chapter 55 - Iteration');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 56, 'Chapter 56 - Subroutines and Recurison');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 57, 'Chapter 57 - Use of an IDE');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 58, 'Chapter 58 - Use of Object-Oriented Techniques');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 59, 'Chapter 59 - Analysis and Design of Algorithms');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 60, 'Chapter 60 - Searching Algorithms');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 61, 'Chapter 61 - Bubble Sort and Insertion Sort');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 62, 'Chapter 62 - Merge Sort and Quick Sort');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 63, 'Chapter 63 - Graph Traversal Algorithms');
insert into `pages` (`chapterContent`, `chapterID`, `chapterTitle`) values ('', 64, 'Chapter 64 - Optimisation Algorithms');
